
spring:
  profiles:
    active: local
---
spring:
  profiles: local
  application:
    name: sba-auth
server:
  servlet:
    context-path: /auth
  port: 8888
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    
# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*" 
      base-path: /actuator
    enabled-by-default: true
  endpoint:
    health:
      show-details: ALWAYS

swagger.enabled: true

feign:
  client:
    config:
      default:
        connect-timeout: 30000
        read-timeout: 20000  
---
spring:
  profiles: k8s
  application:
    name: sba-auth
server:
  servlet:
    context-path: /auth
  port: 8088
  
eureka:
  client:
    service-url:
      defaultZone: http://sba-registry:10001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
    enabled-by-default: true
  endpoint:
    health:
      show-details: ALWAYS

swagger.enabled: true

feign:
  client:
    config:
      default:
        connect-timeout: 30000
        read-timeout: 20000
